import { runHashMap } from "../CustomFunctions/runHashMap";
import money from "../../assets/money.png";

//import runHashMap to generate total amount for each income category;
//Received income && list as props from parent IncomeList: income is the object from database and list is the default category generated by defaultCategory data

const DisplayIncomeCategory = ({ income, list }) => {
  let incomeObject = runHashMap(income, list);

  return (
    <div className="incomeDisplay">
      <h3>Income by Category </h3>
      <ul className="incomeCategory">
        {Object.entries(incomeObject).map((eachIncome) => {
          return (
            <li key={eachIncome[0]}>
              <p className="circle">
                <img className="logo" src={money} alt="wallet" />
              </p>
              <p>{eachIncome[0]}</p>
              <p>${eachIncome[1]}</p>
            </li>
          );
        })}
      </ul>
    </div>
  );
};

export default DisplayIncomeCategory;
