import { runHashMap } from "../CustomFunctions/runHashMap";
import IncomeChart from "./IncomeChart";

//import runHashMap to generate total amount for each income category;
//Received income && list as props from parent IncomeList: income is the object from database and list is the default category generated by defaultCategory data

const DisplayIncomeCategory = ({ income, list }) => {
  let incomeObject = runHashMap(income, list);

  return (
    <div className="incomeDisplay">
      <h3>Income by Category </h3>
      <div className="pieChart">
        <IncomeChart income={incomeObject} />
      </div>
    </div>
  );
};

export default DisplayIncomeCategory;
