import { runHashMap } from "../CustomFunctions/runHashMap";
import money from "../../assets/money.png";
import ExpenseChart from "./ExpenseChart";

//import runHashMap to generate total amount for each expense category;
//Received expense && list as props from parent ExpenseList: expense is the object from database and list is the default category generated by defaultCategory data

const DisplayExpenseCategory = ({ expense, list }) => {
  const expenseObject = runHashMap(expense, list);

  return (
    <div className="expenseCategory">
      <h3>Expense By Category</h3>
      <ul>
        {/* use map to display total amount for each category */}
        {Object.entries(expenseObject).map((eachExpense) => {
          return (
            <li key={eachExpense[0]}>
              <p className="circle">
                <img className="logo" src={money} alt="wallet" />
              </p>
              <p>{eachExpense[0]}</p>
              <p>${eachExpense[1]}</p>
            </li>
          );
        })}
      </ul>
      <ExpenseChart expense={expense} />
    </div>
  );
};

export default DisplayExpenseCategory;
