import { runHashMap } from "../CustomFunctions/runHashMap";
import money from "../../assets/money.png";
import ExpenseChart from "./ExpenseChart";
//import runHashMap to generate total amount for each expense category;
//Received expense && list as props from parent ExpenseList: expense is the object from database and list is the default category generated by defaultCategory data

const ExpenseCategory = ({ expense, list }) => {
  const expenseObject = runHashMap(expense, list);

  return (
    <div className="expenseCategory">
      <h3>Expense By Category</h3>
      <div className="pieChart">
        <ExpenseChart expense={expenseObject} />
      </div>
    </div>
  );
};

export default ExpenseCategory;
